/* eslint-disable @typescript-eslint/no-explicit-any */
 
import { useState, useMemo, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  ArrowLeft, Star, MapPin, Briefcase, GraduationCap, Heart, Sparkles, RefreshCw,
  Calendar, Phone, FileText, Send, Clock, Plus, ChevronRight, Edit3,
  Globe, Users, Shield, Scale, Target, AlertTriangle,
} from 'lucide-react';
import { useCustomerStore } from '@/store/customerStore';
import { useMatchStore } from '@/store/matchStore';
import { cn, getScoreColor, getStatusColor } from '@/utils';
import type { Customer } from '@/types';
import { getCustomerNotes } from '@/firebase/notes';
import { getTimelineEvents } from '@/firebase/timeline';
import type { Note } from '@/types';

const tabs = [
  { id: 'snapshot', label: 'Snapshot' },
  { id: 'profile', label: 'Full Profile' },
  { id: 'notes', label: 'Notes' },
  { id: 'timeline', label: 'Timeline' },
  { id: 'documents', label: 'Documents' },
  { id: 'matches', label: 'Matches' },
];

function SnapshotTab({ customer }: { customer: Customer }) {
  const snapFields = [
    { icon: Heart, label: 'Relationship Goal', value: customer.relationshipGoal, color: 'text-pink-400' },
    { icon: Users, label: 'Family Orientation', value: customer.familyOrientation, color: 'text-violet-400' },
    { icon: Briefcase, label: 'Career Focus', value: customer.careerFocus, color: 'text-blue-400' },
    { icon: Globe, label: 'Lifestyle', value: customer.lifestyleType, color: 'text-emerald-400' },
    { icon: Scale, label: 'Flexibility', value: customer.flexibility, color: 'text-amber-400' },
  ];

  return (
    <div className="space-y-5">
      {/* AI Relationship Snapshot */}
      <div className="glass-card p-5">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-accent" /> AI Relationship Snapshot
            </h3>
            <p className="text-[10px] text-text-muted mt-0.5">Generated by AI based on profile, notes and interactions</p>
          </div>
          <button className="flex items-center gap-1 text-[10px] text-accent-light hover:text-accent transition-colors">
            <RefreshCw className="w-3 h-3" /> Regenerate
          </button>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          {snapFields.map(f => (
            <div key={f.label} className="bg-white/3 rounded-xl p-3 border border-border-secondary">
              <div className="flex items-center gap-1.5 mb-1.5">
                <f.icon className={cn('w-3.5 h-3.5', f.color)} />
                <span className="text-[10px] text-text-muted font-medium">{f.label}</span>
              </div>
              <div className="text-sm font-semibold text-white">{f.value}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Priorities + Deal Breakers */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="glass-card p-5">
          <h3 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
            <Target className="w-4 h-4 text-emerald-400" /> Top Priorities
          </h3>
          <ul className="space-y-2">
            {customer.topPriorities.map(p => (
              <li key={p} className="flex items-start gap-2 text-xs text-text-secondary">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                {p}
              </li>
            ))}
          </ul>
          <button className="flex items-center gap-1 text-xs text-accent-light mt-3 hover:text-accent transition-colors">
            View All Preferences <ArrowLeft className="w-3 h-3 rotate-180" />
          </button>
        </div>

        <div className="glass-card p-5">
          <h3 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
            <AlertTriangle className="w-4 h-4 text-red-400" /> Deal Breakers
          </h3>
          <ul className="space-y-2">
            {customer.dealBreakers.map(d => (
              <li key={d} className="flex items-start gap-2 text-xs text-text-secondary">
                <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
                {d}
              </li>
            ))}
          </ul>
          <button className="flex items-center gap-1 text-xs text-accent-light mt-3 hover:text-accent transition-colors">
            View All Deal Breakers <ArrowLeft className="w-3 h-3 rotate-180" />
          </button>
        </div>
      </div>

      {/* Quick Info */}
      <div className="glass-card p-5">
        <h3 className="text-sm font-bold text-white mb-3">Quick Information</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {[
            { icon: Calendar, label: 'Date of Birth', value: customer.dob },
            { icon: Globe, label: 'Languages', value: customer.languages.join(', ') },
            { icon: GraduationCap, label: 'Height', value: customer.height },
            { icon: GraduationCap, label: 'Education', value: customer.education },
            { icon: Briefcase, label: 'Company', value: customer.company },
            { icon: MapPin, label: 'Work Location', value: `${customer.city}, ${customer.state}` },
          ].map(info => (
            <div key={info.label} className="text-center p-2">
              <info.icon className="w-4 h-4 text-text-muted mx-auto mb-1" />
              <div className="text-[10px] text-text-muted mb-0.5">{info.label}</div>
              <div className="text-xs font-medium text-text-secondary truncate">{info.value}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function FullProfileTab({ customer }: { customer: Customer }) {
  const fields = [
    { label: 'Full Name', value: customer.name },
    { label: 'Date of Birth', value: customer.dob },
    { label: 'Age', value: `${customer.age} years` },
    { label: 'Gender', value: customer.gender },
    { label: 'Height', value: customer.height },
    { label: 'Weight', value: customer.weight },
    { label: 'City', value: customer.city },
    { label: 'State', value: customer.state },
    { label: 'Profession', value: customer.profession },
    { label: 'Company', value: customer.company },
    { label: 'Income', value: customer.income },
    { label: 'Education', value: customer.education },
    { label: 'Languages', value: customer.languages.join(', ') },
    { label: 'Religion', value: customer.religion },
    { label: 'Caste', value: customer.caste },
    { label: 'Marital Status', value: customer.maritalStatus },
    { label: 'Children', value: customer.children },
    { label: 'Pets', value: customer.pets },
    { label: 'Relocation', value: customer.relocation },
    { label: 'Dietary Preference', value: customer.dietaryPreference },
    { label: 'Smoking', value: customer.smokingHabit },
    { label: 'Drinking', value: customer.drinkingHabit },
    { label: 'Hobbies', value: customer.hobbies.join(', ') },
  ];

  return (
    <div className="glass-card p-5">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-bold text-white">Complete Profile Details</h3>
        <button className="btn-secondary text-xs py-1.5 px-3 flex items-center gap-1">
          <Edit3 className="w-3 h-3" /> Edit
        </button>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {fields.map(f => (
          <div key={f.label} className="p-3 rounded-xl bg-white/3 border border-border-secondary">
            <div className="text-[10px] text-text-muted mb-1">{f.label}</div>
            <div className="text-sm text-white font-medium truncate">{f.value}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

function NotesTab({ customer }: { customer: Customer }) {
  const [notes, setNotes] = useState<Note[]>([]);
  const [isLoadingNotes, setIsLoadingNotes] = useState(true);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsLoadingNotes(true);
    getCustomerNotes(customer.id)
      .then(setNotes)
      .catch(() => {
        // Fallback to static notes if Firestore fails
        setNotes([
          { id: '1', customerId: customer.id, content: `${customer.name} is open to professionals and values family time on weekends. Prefers a partner who is calm and understanding.`, author: 'Matchmaker', createdAt: '2024-04-15', updatedAt: '2024-04-15' },
          { id: '2', customerId: customer.id, content: 'Updated preferences after second call. More open to relocation now. Wants partner in tech or finance.', author: 'Matchmaker', createdAt: '2024-04-22', updatedAt: '2024-04-22' },
        ]);
      })
      .finally(() => setIsLoadingNotes(false));
  }, [customer.id, customer.name]);

  return (
    <div className="space-y-4">
      <div className="glass-card p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-bold text-white">Recent Notes</h3>
          <button className="flex items-center gap-1 text-xs text-accent-light hover:text-accent transition-colors">View All</button>
        </div>
        {isLoadingNotes ? (
          <div className="animate-pulse space-y-3">
            {[1, 2].map(i => <div key={i} className="h-24 bg-white/5 rounded-xl" />)}
          </div>
        ) : (
          <div className="space-y-3">
            {notes.map(n => (
              <div key={n.id} className="p-4 rounded-xl bg-white/3 border border-border-secondary">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-medium text-white">{new Date(n.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</span>
                </div>
                <p className="text-xs text-text-secondary leading-relaxed">{n.content}</p>
                <div className="flex items-center gap-2 mt-2">
                  <div className="w-5 h-5 rounded-full gradient-accent flex items-center justify-center text-[8px] text-white font-bold">S</div>
                  <span className="text-[10px] text-text-muted">{n.author}</span>
                </div>
              </div>
            ))}
          </div>
        )}
        <button className="w-full mt-3 btn-secondary text-xs py-2.5 flex items-center justify-center gap-1">
          <Plus className="w-3.5 h-3.5" /> Add Note
        </button>
      </div>
    </div>
  );
}

function TimelineTab({ customer }: { customer: Customer }) {
  const [events, setEvents] = useState<{ icon: unknown; label: string; date: string; color: string }[]>([]);

  useEffect(() => {
    getTimelineEvents(customer.id)
      .then((fbEvents) => {
        if (fbEvents.length > 0) {
           
          const iconMap: Record<string, any> = {
            profile_verified: Shield,
            call_completed: Phone,
            preferences_updated: FileText,
            match_sent: Send,
            meeting_scheduled: Calendar,
            note_added: FileText,
            follow_up: Calendar,
          };
          const colorMap: Record<string, string> = {
            profile_verified: 'text-emerald-400 bg-emerald-500/15',
            call_completed: 'text-blue-400 bg-blue-500/15',
            preferences_updated: 'text-amber-400 bg-amber-500/15',
            match_sent: 'text-violet-400 bg-violet-500/15',
            meeting_scheduled: 'text-pink-400 bg-pink-500/15',
            note_added: 'text-blue-400 bg-blue-500/15',
            follow_up: 'text-pink-400 bg-pink-500/15',
          };
          setEvents(fbEvents.map(e => ({
            icon: iconMap[e.type] || FileText,
            label: e.title,
            date: new Date(e.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
            color: colorMap[e.type] || 'text-blue-400 bg-blue-500/15',
          })));
        } else {
          // Fallback
          setEvents([
            { icon: Shield, label: 'Profile Verified', date: '12 Apr 2024', color: 'text-emerald-400 bg-emerald-500/15' },
            { icon: Phone, label: 'First Call Completed', date: '15 Apr 2024', color: 'text-blue-400 bg-blue-500/15' },
            { icon: FileText, label: 'Preferences Updated', date: '18 Apr 2024', color: 'text-amber-400 bg-amber-500/15' },
            { icon: Send, label: 'Match Sent', date: '21 Apr 2024', color: 'text-violet-400 bg-violet-500/15' },
            { icon: Calendar, label: 'Follow-up Scheduled', date: '25 Apr 2024', color: 'text-pink-400 bg-pink-500/15' },
          ]);
        }
      })
      .catch(() => {
        setEvents([
          { icon: Shield, label: 'Profile Verified', date: '12 Apr 2024', color: 'text-emerald-400 bg-emerald-500/15' },
          { icon: Phone, label: 'First Call Completed', date: '15 Apr 2024', color: 'text-blue-400 bg-blue-500/15' },
          { icon: FileText, label: 'Preferences Updated', date: '18 Apr 2024', color: 'text-amber-400 bg-amber-500/15' },
          { icon: Send, label: 'Match Sent', date: '21 Apr 2024', color: 'text-violet-400 bg-violet-500/15' },
          { icon: Calendar, label: 'Follow-up Scheduled', date: '25 Apr 2024', color: 'text-pink-400 bg-pink-500/15' },
        ]);
      });
  }, [customer.id]);

  return (
    <div className="glass-card p-5">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <Clock className="w-4 h-4 text-text-muted" /> Timeline
        </h3>
        <button className="text-xs text-accent-light hover:text-accent transition-colors">View All</button>
      </div>
      <div className="relative">
        <div className="absolute left-5 top-2 bottom-2 w-px bg-border-secondary" />
        <div className="space-y-4">
          {events.map((e, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.05 }}
              className="flex items-center gap-4 relative pl-2"
            >
              <div className={cn('w-8 h-8 rounded-full flex items-center justify-center z-10 shrink-0', e.color)}>
                {(() => { const Icon = e.icon as any; return <Icon className="w-4 h-4" />; })()}
              </div>
              <div className="flex-1">
                <div className="text-sm font-medium text-white">{e.label}</div>
                <div className="text-xs text-text-muted">{e.date}</div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}

function DocumentsTab() {
  return (
    <div className="glass-card p-8 text-center">
      <FileText className="w-12 h-12 text-text-muted mx-auto mb-3" />
      <h3 className="text-sm font-medium text-white mb-1">No documents uploaded</h3>
      <p className="text-xs text-text-muted mb-4">Upload ID proofs, photos, or other documents</p>
      <button className="btn-primary text-xs">Upload Document</button>
    </div>
  );
}

function MatchesTab({ customer }: { customer: Customer }) {
  const { matches, fetchMatchesByCustomer, isLoading } = useMatchStore();
  const { customers } = useCustomerStore();
  const navigate = useNavigate();

  useEffect(() => {
    fetchMatchesByCustomer(customer.id);
  }, [customer.id, fetchMatchesByCustomer]);

  return (
    <div className="space-y-3">
      {isLoading ? (
        <div className="animate-pulse space-y-3">
          {[1, 2, 3].map(i => <div key={i} className="h-16 bg-white/5 rounded-2xl" />)}
        </div>
      ) : matches.length > 0 ? matches.slice(0, 5).map(match => {
        const otherId = match.customerId === customer.id ? match.matchedCustomerId : match.customerId;
        const other = customers.find(c => c.id === otherId);
        if (!other) return null;
        return (
          <div key={match.id} className="glass-card p-4 flex items-center gap-3 hover:border-border-hover transition-colors cursor-pointer">
            <img src={other.photo} alt={other.name} className="w-11 h-11 rounded-full bg-bg-tertiary shrink-0" />
            <div className="flex-1 min-w-0">
              <div className="text-sm font-semibold text-white truncate">{other.name}</div>
              <div className="text-xs text-text-muted">{other.age} • {other.city} • {other.profession}</div>
            </div>
            <div className="text-right shrink-0">
              <div className={cn('text-lg font-bold', getScoreColor(match.compatibilityScore))}>{match.compatibilityScore}%</div>
              <div className="text-[10px] text-text-muted">Match</div>
            </div>
          </div>
        );
      }) : (
        <div className="glass-card p-8 text-center">
          <Heart className="w-12 h-12 text-text-muted mx-auto mb-3" />
          <p className="text-sm text-text-muted">No matches yet</p>
          <button onClick={() => navigate('/match-studio')} className="btn-primary text-xs mt-3">Go to Match Studio</button>
        </div>
      )}
    </div>
  );
}

export default function CustomerWorkspace() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('snapshot');
  const { customers, fetchCustomerById, fetchCustomers } = useCustomerStore();

  const customer = useMemo(() => {
    if (id) {
      return customers.find(c => c.id === id);
    }
    return customers[0];
  }, [id, customers]);

  useEffect(() => {
    if (customers.length === 0) {
      fetchCustomers();
    } else if (id && !customer) {
      fetchCustomerById(id);
    }
  }, [id, customer, customers.length, fetchCustomers, fetchCustomerById]);

  if (!customer) {
    return (
      <div className="p-8 text-center">
        <div className="w-8 h-8 border-2 border-accent/30 border-t-accent rounded-full animate-spin mx-auto mb-4" />
        <p className="text-sm text-text-muted">Loading customer...</p>
      </div>
    );
  }

  const renderTab = () => {
    switch (activeTab) {
      case 'snapshot': return <SnapshotTab customer={customer} />;
      case 'profile': return <FullProfileTab customer={customer} />;
      case 'notes': return <NotesTab customer={customer} />;
      case 'timeline': return <TimelineTab customer={customer} />;
      case 'documents': return <DocumentsTab />;
      case 'matches': return <MatchesTab customer={customer} />;
      default: return <SnapshotTab customer={customer} />;
    }
  };

  return (
    <div className="p-4 lg:p-6 pb-24 lg:pb-6 space-y-4">
      {/* Back + Actions */}
      <div className="flex items-center justify-between">
        <button onClick={() => navigate('/customers')} className="flex items-center gap-2 text-sm text-text-muted hover:text-text-secondary transition-colors">
          <ArrowLeft className="w-4 h-4" /> Customers <ChevronRight className="w-3 h-3" /> <span className="text-white">{customer.name}</span>
        </button>
        <div className="flex items-center gap-2">
          <button className="btn-secondary text-xs py-1.5 px-3">Edit Profile</button>
          <button className="btn-primary text-xs py-1.5 px-3">Actions ▾</button>
        </div>
      </div>

      {/* Profile Header */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-card p-5"
      >
        <div className="flex flex-col sm:flex-row items-start gap-4">
          <img src={customer.photo} alt={customer.name} className="w-20 h-20 rounded-2xl bg-bg-tertiary shrink-0" />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <h1 className="text-xl font-bold text-white">{customer.name}</h1>
              {customer.verified && <span className="text-accent text-sm">✓</span>}
              <Star className="w-4 h-4 text-text-muted cursor-pointer hover:text-amber-400 transition-colors" />
            </div>
            <p className="text-xs text-text-muted mt-1">
              {customer.age} • {customer.city}, {customer.state} • {customer.profession}
            </p>
            <p className="text-[10px] text-text-muted mt-0.5">
              ID: {customer.id} • Joined {customer.joinedDate}
            </p>
            <div className="flex items-center gap-2 mt-2 flex-wrap">
              <span className={cn('badge', getStatusColor(customer.status))}>{customer.status}</span>
              <span className="badge badge-purple">{customer.religion}</span>
              <span className="badge badge-blue">{customer.maritalStatus}</span>
              <span className="badge badge-green">{customer.relocation}</span>
            </div>
          </div>

          {/* AI Score */}
          <div className="flex items-center gap-4 shrink-0">
            <div className="text-center">
              <div className="relative w-20 h-20">
                <svg className="w-20 h-20 -rotate-90" viewBox="0 0 80 80">
                  <circle cx="40" cy="40" r="35" fill="none" stroke="rgba(139,92,246,0.1)" strokeWidth="5" />
                  <circle
                    cx="40" cy="40" r="35" fill="none"
                    stroke={customer.aiScore >= 85 ? '#10B981' : customer.aiScore >= 70 ? '#8B5CF6' : '#F59E0B'}
                    strokeWidth="5" strokeLinecap="round"
                    strokeDasharray={`${customer.aiScore * 2.2} 220`}
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className={cn('text-lg font-bold', getScoreColor(customer.aiScore))}>{customer.aiScore}%</span>
                </div>
              </div>
              <div className="text-[10px] text-text-muted mt-1">AI Match Potential</div>
              <div className="text-[10px] text-emerald-400">High Confidence</div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Tabs */}
      <div className="flex gap-1 overflow-x-auto no-scrollbar border-b border-border-secondary pb-px">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={cn(
              'shrink-0 px-4 py-2.5 text-sm font-medium transition-all duration-150 border-b-2 -mb-px',
              activeTab === tab.id
                ? 'text-accent-light border-accent'
                : 'text-text-muted border-transparent hover:text-text-secondary'
            )}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <motion.div
        key={activeTab}
        initial={{ opacity: 0, y: 5 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.15 }}
      >
        {renderTab()}
      </motion.div>
    </div>
  );
}
